#!/bin/bash
#git clone --branch sans_user_agent --single-branch https://github.com/TiBillet/client-raspberry-cashless-LaBoutik.git

#TODO: pour le script final remplacer par $x
nfc="gpio"

# update
echo "----- Update system"
apt-get update && sudo apt-get -y upgrade

# install divers
apt list --installed > log1

echo "----- install 7Zip"
apt-get install p7zip-full -y
echo "----- install git" -y
apt-get install git -yS
echo "----- install nano"
apt-get install nano -y

echo "----- install chromium...Prends un café c'est un peut long :) "
apt-get install chromium-browser -y

apt list --installed > log2
sort log1 log2 | uniq -u > log-install-divers.txt && rm -fr log1 && rm -fr log2

# TODO: rapatrier le git "sans_user_agent"


# install node 20.xx
apt list --installed > log1

echo "----- install gcc"
apt-get install gcc -y
echo "----- install g++"
apt-get install g++ -y
echo "----- install make"
apt-get install make -y
echo "----- install apt-transport-https"
apt-get install apt-transport-https -y

apt-get install -y ca-certificates curl gnupg -y
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/nodesource.gpg
NODE_MAJOR=20
echo "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
apt-get update
apt-get install nodejs -y

apt list --installed > log2
sort log1 log2 | uniq -u > log-install-node20.txt && rm -fr log1 && rm -fr log2

# addon nodejs
npm install -g node-gyp
npm install -g rebuild

# install X11 + openbox
apt list --installed > log1

echo "----- installxorg"
apt-get install xserver-xorg -y
echo "----- install x11"
apt-get install x11-xserver-utils -y
echo "----- install xinit"
apt-get install xinit -y
echo "----- install fbturbo"
apt-get install xserver-xorg-video-fbturbo -y
echo "----- install xdtool"
apt-get install xdotool -y
echo "----- install openbox"
apt-get install openbox -y

apt list --installed > log2
sort log1 log2 | uniq -u > log-install-x11-openbox.txt && rm -fr log1 && rm -fr log2

# config startx
if grep "#modif bashrc = ok" /home/sysop/.bashrc > /dev/null
then
 echo 'bashrc déjà modifié pour auto startx !'
else
 echo 'export TYPE_SERVEUR_NFC=VMA405' >> /home/sysop/.bashrc
 echo '#modif bashrc = ok' >> /home/sysop/.bashrc
 echo '[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && startx -- -nocursor' >> /home/sysop/.bashrc
fi

# nfc usb et gpio
if [ $nfc = 'gpio' ]
then
  # gpio
  echo "dtparam=spi=on" >> /boot/config.txt
  usermod -a -G gpio $USER
  usermod -a -G spi $USER
  usermod -a -G netdev $USER
  chown root:gpio /dev/gpiomem
  chmod g+rw /dev/gpiomem
  rm -fr /etc/modprobe.d/blacklist-nfc-usb.conf
else
  # usb
  echo "install libpcsclite1"
  apt-get install libpcsclite1 -y
  echo "install libpcsclite-dev"
  apt-get install libpcsclite-dev -y
  echo "install pcscd"
  apt-get install pcscd -y
  echo "install pcsc-tools"
  apt-get install pcsc-tools -y
  # configuration
  echo "install nfc /bin/false" > /etc/modprobe.d/blacklist-nfc-usb.conf
  echo "install pn533 /bin/false"  >> /etc/modprobe.d/blacklist-nfc-usb.conf
  chown root:root /etc/modprobe.d/blacklist-nfc-usb.conf
  chmod 0644 /etc/modprobe.d/blacklist-nfc-usb.conf
fi

# creation .env.js
echo "----- Création .env.js"
echo "export const env = {" > ./nfcServer/.env.js
if [ $nfc = 'gpio' ]
then
  # gpio
  echo '  '\"device\": \"vma405-rfid-rc522\",  >> ./nfcServer/.env.js
else
  # usb
  echo '  '\"device\": \"acr122u-u9\",  >> ./nfcServer/.env.js
fi

echo '  '\"server_pin_code\": \"https://discovery.tibillet.coop\",  >> ./nfcServer/.env.js
echo '  '\"hostname\": \"$(hostname)\", >> ./nfcServer/.env.js
echo '  '\"front_type\": \"FOR\", >> ./nfcServer/.env.js
echo '  '\"mode_nfc\": \"NFCLO\", >> ./nfcServer/.env.js
echo '  '\"current_server\": \"\", >> ./nfcServer/.env.js
echo '  '\"servers\": [], >> ./nfcServer/.env.js
echo '  '\"exeChromium\": \"chromium-browser\", >> ./nfcServer/.env.js
echo '  '\"dev\": true >> ./nfcServer/.env.js
echo "}" >> ./nfcServer/.env.js

# creation package.json
echo "----- Création package.json"
JSON_STRING='{
"name":"client-raspberry-cashless-laboutik",
"version":"1.0.0",
"description":"serveur nfc",
"main":"serveur_nfc.js",
"type":"module",
"license": "ISC",
"dependencies":{
  "ip": "^1.1.8","socket.io": "^4.7.2",
  "@sentry/node": "^7.106.0","@sentry/profiling-node": "^7.106.0",
  "slugify": "^1.6.6",
  "http-proxy": "^1.18.1",'

if [ $nfc = 'gpio' ]
  then
    # gpio
    JSON_STRING2='"rpi-softspi": "^1.0.5", "rpio": "^2.4.2"}}'
  else
    # usb
    JSON_STRING2='"nfc-pcsc": "^0.8.1"}}'
  fi

echo "${JSON_STRING}" > ./nfcServer/package.json
echo "${JSON_STRING2}" >> ./nfcServer/package.json

# installation of nfc server modules
cd nfcServer
npm i

#TODO: ajouter partie rotation écran

Autologin mode console
raspi-config nonint do_boot_behaviour B2

# en mode test pour le moment
echo '[Unit]' > /etc/systemd/system/nodejs-nfcServer.service
echo 'Description=NFC server listen 0.0.0.0 port 3000' >> /etc/systemd/system/nodejs-nfcServer.service
echo 'After=networking.service' >> /etc/systemd/system/nodejs-nfcServer.service
echo 'Requires=network.target' >> /etc/systemd/system/nodejs-nfcServer.service
echo 'PartOf=graphical-session.target' >> /etc/systemd/system/nodejs-nfcServer.service
echo '' >> /etc/systemd/system/nodejs-nfcServer.service
echo '[Service]' >> /etc/systemd/system/nodejs-nfcServer.service
echo 'Environment=NFC_SERVER_PORT=3000' >> /etc/systemd/system/nodejs-nfcServer.service
echo 'Type=simple' >> /etc/systemd/system/nodejs-nfcServer.service
echo 'WorkingDirectory=/home/sysop/nfcServer/' >> /etc/systemd/system/nodejs-nfcServer.service
echo 'Restart=on-failure' >> /etc/systemd/system/nodejs-nfcServer.service
echo 'ExecStart=/usr/bin/node nfcServer.js' >> /etc/systemd/system/nodejs-nfcServer.service
echo '' >> /etc/systemd/system/nodejs-nfcServer.service
echo '[Install]' >> /etc/systemd/system/nodejs-nfcServer.service
echo 'WantedBy=graphical-session.target' >> /etc/systemd/system/nodejs-nfcServer.service

# activation service
#systemctl enable nodejs-nfcServer.service 
#systemctl start nodejs-nfcServer.service
#systemctl status nodejs-nfcServer.service

reboot
