#!/bin/bash

echo DISPLAY=:0 xdotool getactivewindow key F5 > /etc/xdg/openbox/autostart
echo  >> /etc/xdg/openbox/autostart
echo '# stop veille/économie dénergie' >> /etc/xdg/openbox/autostart
echo 'xset dpms 0 0 0 && xset s noblank  && xset s off' >> /etc/xdg/openbox/autostart
echo  >> /etc/xdg/openbox/autostart
echo '# vidage du cache chromium' >> /etc/xdg/openbox/autostart
echo rm -fr /home/sysop/.cache/chromium >> /etc/xdg/openbox/autostart
echo rm -fr /home/sysop/.config/chromium/Default/ >> /etc/xdg/openbox/autostart
echo  >> /etc/xdg/openbox/autostart
echo '# lance le seveur nfc' >> /etc/xdg/openbox/autostart
echo cd /home/sysop/client-raspberry-cashless-LaBoutik/nfcServer/ >> /etc/xdg/openbox/autostart
echo node nfcServer.js  >> /etc/xdg/openbox/autostart

chown root:root /etc/xdg/openbox/autostart
chmod 755 /etc/xdg/openbox/autostart
